from enum import Enum


class RCBillingCurrency(str, Enum):
    AED = "AED"
    AUD = "AUD"
    BRL = "BRL"
    CAD = "CAD"
    CHF = "CHF"
    CLP = "CLP"
    CNY = "CNY"
    COP = "COP"
    CRC = "CRC"
    CZK = "CZK"
    DKK = "DKK"
    EUR = "EUR"
    GBP = "GBP"
    GEL = "GEL"
    HKD = "HKD"
    HUF = "HUF"
    IDR = "IDR"
    ILS = "ILS"
    IQD = "IQD"
    JOD = "JOD"
    JPY = "JPY"
    KES = "KES"
    KRW = "KRW"
    KZT = "KZT"
    MAD = "MAD"
    MXN = "MXN"
    MYR = "MYR"
    NOK = "NOK"
    NZD = "NZD"
    PEN = "PEN"
    PHP = "PHP"
    PLN = "PLN"
    QAR = "QAR"
    RON = "RON"
    RSD = "RSD"
    SAR = "SAR"
    SEK = "SEK"
    SGD = "SGD"
    THB = "THB"
    TRY = "TRY"
    TWD = "TWD"
    TZS = "TZS"
    UAH = "UAH"
    USD = "USD"
    VND = "VND"
    ZAR = "ZAR"

    def __str__(self) -> str:
        return str(self.value)
